## Лабораторна робота 3  

### Частина 1. Класифікація пацієнтів за ризиком серцево-судинних захворювань
У першій частині роботі ви будете використовувати медичний набір даних для прогнозування серцево-судинних захворювань. Ці дані містять інформацію про пацієнтів (вік, тиск, рівень холестерину, результати ЕКГ, наявність стенокардії тощо), а також мітку, яка вказує, чи має пацієнт серцеве захворювання.
Метою є побудова моделі класифікації, яка допоможе визначити ризик серцевої патології.  

**Опис змінних:**  
Age – вік пацієнта (у роках).  
Sex – стать пацієнта: M – чоловік, F – жінка.  
ChestPainType – тип болю у грудях:  
- TA – типова стенокардія,  
- ATA – атипова стенокардія,  
- NAP – біль не пов'язаний із серцем,  
- ASY – безсимптомний.
  
RestingBP – артеріальний тиск у стані спокою (мм рт. ст.).  
Cholesterol – рівень холестерину у крові (мг/дл).  
FastingBS – рівень цукру в крові натще: 1, якщо > 120 мг/дл; 0 – інакше.  
RestingECG – результати електрокардіограми у стані спокою:  
- Normal – норма,  
- ST – відхилення ST-T (аномалії зубця T або сегмента ST),  
- LVH – гіпертрофія лівого шлуночка.
  
MaxHR – максимальна досягнута частота серцевих скорочень (від 60 до 202).  
ExerciseAngina – наявність стенокардії, викликаної фізичним навантаженням: Y – так, N – ні.  
Oldpeak – ступінь депресії сегмента ST (числове значення, показує відхилення на ЕКГ). Чим більше значення – тим вищий ризик серцевої патології.  
ST_Slope – нахил сегмента ST на ЕКГ (показує реакцію серця на навантаження):  
- Up – висхідний (нормальна реакція),  
- Flat – плоский (можлива ішемія чи відхилення),  
- Down – низхідний (ознака патології, часто ішемічна хвороба).
  
HeartDisease – цільова змінна: 1 – наявне серцеве захворювання, 0 – пацієнт здоровий.

In [2]:
import pandas as pd
df = pd.read_csv('heart.csv')
df.head()

,Unnamed: 0,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,19,36.0,M,ATA,120,267.0,0.0,Normal,160.0,N,3.0,Flat,1
1,337,63.0,M,ASY,150,0.0,1.0,ST,154.0,N,3.7,Up,1
2,800,43.0,M,NAP,130,315.0,0.0,Normal,162.0,N,1.9,Up,0
3,233,41.0,M,ASY,112,250.0,0.0,Normal,142.0,N,0.0,Up,0
4,266,52.0,M,ASY,130,298.0,0.0,Normal,110.0,Y,1.0,Flat,1

### Завдання  

1. Виконайте попередню обробку даних. При виконанні обробки пам'ятайте про проблему витоку даних.  
2. Розбийте дані на навчальну та тестову вибірки.
3. Оберіть модель класифікації.
4. Навчіть модель на навчальній вибірці.
3. Оцініть якість моделі на тестовій вибірці (метрику для оцінювання точності класифікації оберіть самостійно).
5. Повторіть експеримент кілька разів із різними значеннями `random_state` при розбитті на навчальну та тестову вибірки.
6. Виведіть отримані метрики за різних варіантів розбиття на екран.  
7. Використайте ту саму модель та той самий набір даних:  
- застосуйте k-блочну перехресну перевірку для:
   - \( k = 5 \)
   - \( k = 10 \)
   - \( k = 15 \)  
- для кожного значення \( k \) обчисліть середнє значення та стандартне відхилення обраної вами метрики.

Коротко порівняйте отримані результати.

### Частина 2. Регресія: вибір моделі та аналіз витоку даних  

У другій частині практичної роботи ви розглянете процес побудови моделі з використанням навчальної, валідаційної та тестової вибірок.  
_У реальних задачах цей процес зазвичай автоматизується за допомогою перехресної перевірки._  
Однак у даній роботі розбиття виконується вручну для кращого розуміння:  
- ролі кожної вибірки;
- впливу витоку даних на якість моделі.

Набір даних **Auto** містить інформацію про автомобілі та їх технічні характеристики:  
- `mpg` — витрати пального **цільова змінна**;  
- `cylinders` - кількість циліндрів двигуна;
- `displacement` - об’єм двигуна;
- `horsepower` - потужність двигуна;
- `weight` - вага автомобіля;
- `acceleration` - час розгону;
- `year` - рік випуску;
- `origin` - країна походження (категоріальна змінна);
- `name` - назва автомобіля.
---

### Завдання

1. Розбийте дані на вибірки:
- навчальна — 60% або 70%;
- валідаційна — 20% або 15%;
- тестова — 20% або 15%.  
2. Виконайте попередню обробку (! усі операції повинні виконуватися після розбиття даних). Оскільки на наступному кроці ви будете використовувати метод k найближчих сусідів, який ґрунтується на обчисленні відстаней між об’єктами, перед навчанням необхідно виконати масштабування числових ознак.  
3. Використайте модель KNeighborsRegressor. Переберіть значення параметра `n_neighbors` (наприклад: 1, 3, 5, 7, 9, 11, 13, 15). Для кожного значення:  
   - навчіть модель на навчальній вибірці;
   - оцініть якість моделі на валідаційній вибірці.
4. Оберіть найкраще значення параметра та побудуйте графік залежності помилок на навчальній та тестовій вибірках від `n_neighbors`.
5. Фінальна оцінка моделі  
- Візьміть модель, обрану на валідаційній вибірці.
- Оцініть її якість на тестовій вибірці.

---

6. Експеримент з витоком даних  
Повторіть процес побудови моделі, але цього разу виконайте попередню обробку некоректно: до розбиття на навчальну, валідаційну та тестову вибірки виконайте попередню обробку даних на всьому наборі даних.

7. Після цього:
   - виконайте розбиття даних;
   - повторіть вибір моделі;
   - оцініть її якість на  тестовій вибірці.

Порівняйте результати:
- моделі, побудованої без витоку даних;
- моделі, побудованої з витоком даних.

In [3]:
auto = pd.read_csv('auto.csv')
auto.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1

In [9]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler
)

from sklearn.impute import SimpleImputer

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [10]:
auto = pd.read_csv('auto.csv')

print(auto.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70
1  15.0          8         350.0         165    3693          11.5    70
2  18.0          8         318.0         150    3436          11.0    70
3  16.0          8         304.0         150    3433          12.0    70
4  17.0          8         302.0         140    3449          10.5    70

   origin
0       1
1       1
2       1
3       1
4       1

In [11]:
# Видалення пропусків
auto = auto.dropna()

print(auto.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
year            0
origin          0
dtype: int64

In [12]:
X = auto.drop('mpg', axis=1)
y = auto['mpg']

# Видаляємо name лише якщо він існує
if 'name' in X.columns:
    X = X.drop('name', axis=1)

print(X.head())

   cylinders  displacement  horsepower  weight  acceleration  year  origin
0          8         307.0         130    3504          12.0    70       1
1          8         350.0         165    3693          11.5    70       1
2          8         318.0         150    3436          11.0    70       1
3          8         304.0         150    3433          12.0    70       1
4          8         302.0         140    3449          10.5    70       1

In [13]:
numeric_features = X.select_dtypes(
    include=['int64', 'float64']
).columns

categorical_features = X.select_dtypes(
    include=['object']
).columns

print("Числові ознаки:")
print(numeric_features)

print("\nКатегоріальні ознаки:")
print(categorical_features)

Числові ознаки:
Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'year', 'origin'],
      dtype='object')

Категоріальні ознаки:
Index([], dtype='object')

In [14]:
# Числові ознаки
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Категоріальні ознаки
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Загальний препроцесор
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [15]:
X_temp, X_test, y_temp, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=0.25,
    random_state=42
)

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (234, 7)
Validation: (79, 7)
Test: (79, 7)

In [16]:
# Лінійна регресія
lin_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

# Random Forest
rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

models = {
    'Linear Regression': lin_model,
    'Random Forest': rf_model
}

In [17]:
reg_results = []

for name, mdl in models.items():

    # Навчання моделі
    mdl.fit(X_train, y_train)

    # Прогноз
    y_val_pred = mdl.predict(X_val)

    # Метрики
    mae = mean_absolute_error(y_val, y_val_pred)

    rmse = np.sqrt(
        mean_squared_error(y_val, y_val_pred)
    )

    r2 = r2_score(y_val, y_val_pred)

    # Збереження результатів
    reg_results.append([name, mae, rmse, r2])

    # Виведення
    print("\nМодель:", name)
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"R2: {r2:.4f}")

Модель: Linear Regression
MAE: 2.1966
RMSE: 2.8429
R2: 0.8329

Модель: Random Forest
MAE: 2.0312
RMSE: 3.0946
R2: 0.8020

In [18]:
reg_results_df = pd.DataFrame(
    reg_results,
    columns=['Model', 'MAE', 'RMSE', 'R2']
)

print(reg_results_df)

               Model       MAE      RMSE        R2
0  Linear Regression  2.196578  2.842882  0.832903
1      Random Forest  2.031203  3.094616  0.802000